title: Cherise Stanley # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Passionate about learning through self-development. 
  <br><br>
  Developing lifelong skills in data science, software development, engineering, and mathematics. 
  <br><br>

  

google_analytics: G-2TRYTQMQEW # your Google Analytics tracking ID here
